Added completed task from lesson 4
eugene-okulik/A_lex pull request #3
Opened 2024-11-30 13:57 UTC by aBarashvili

2024-11-30 14:02 UTC, aBarashvili commented
Корректно ли на 9 строке таким образом добавлять в словарь словаря ключ: значение ??

`my_dict['dict']['i am a tuple'] = 123`

2024-12-01 09:28 UTC, eugene-okulik requested changes
Всё отлично, но проверку на внимательность не прошел ))

2024-12-01 09:28 UTC, eugene-okulik commented on homework/alexander_barashvili/lesson_4/lesson_4_task.py
> +my_dict['dict']['i am a tuple'] = 123
Корректно так добавлять. Но есть один нюанс именно по заданию  
В задании было:

> добавьте элемент с ключом ('i am a tuple',) и любым значением

У тебя выполнено как если бы там было

> добавьте элемент с ключом 'i am a tuple' и любым значением

`('i am a tuple',) ` - кортеж с одним элементом. И именно это и должно быть ключом. Сейчас ключ - строка `'i am a tuple'`

2024-12-01 10:05 UTC, eugene-okulik approved these changes

2024-12-01 10:05 UTC, merged